### ISSUE TITLE
차량, 예약 API 추가분 문의

### ISSUE THREAD

**Issue by im2187** [hwahyeon/web-rent-mycar#3]
차량등록에 대해 회의할때 등록된 차량에 대한 정보수정과 삭제에 대해 합의가 안된거 같아서 차량정보 수정과 삭제부분 API를 넣어야 하는지에 대해서 어떻게 생각하십니까?

달력에서 날짜 선택하고 렌트 예약 일정 등록 할때 예약 변경이나 취소의 경우도 있어서 렌트 예약 수정이랑 예약 취소 부분 API 도 넣어야하나해서 어떻게 생각하십니까?

**Comment by hwahyeon** [comment]
말씀대로 차량 정보 수정과 삭제 부분에 대한 API와 예약 수정, 예약 취소 부분에 대한 API 둘 다 필요합니다.

추가로 주행거리 수정에 관한 API도 필요하다고 생각합니다.
· 자동차 등록 시 주행거리 입력
· 자동차 예약 시 예상 주행거리 입력
· 자동차 반납 시 실제 주행거리 입력
이 프로세서를 넣으려고 하니, 주행거리 수정에 관한 API도 부탁합니다.

**Comment by im2187** [comment]
네 알겠습니다.
말씀해주신 주행거리 수정에 관한 API도 추가하도록 하겠습니다.

**Comment by hwahyeon** [comment]
본 수정 내용 확인 완료
